config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :surveys, param: :token, path: ''
  resources :participations, only: %i[create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/field.rb
class Field < ApplicationRecord
  belongs_to :survey

  TYPES = %w[checkbox select text].freeze

  jsonb_accessor :options,
    values:  [array: true, default: []],
    required: [:boolean, default: false]

  validates :name, presence: true
  validates :type, inclusion: { in: TYPES }

  def self.inheritance_column
    'sti_type'
  end

  # query options
  # Field.where("options @> '{\"a\": 1}'")
  # Field.where('options @> ?', { a: 1 }.to_json)
  # Field.where("options->>'a' = ?", "1").explain
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :survey

  validate :validate_answers

  def render
    ApplicationController.render(partial: 'surveys/participation', locals: { participation: self })
  end

  private

  def validate_answers
    survey.fields.each do |field|
      if field.required? && answers[field.name].blank?
        errors.add field.name, 'must not be blank'
      end
    end
  end
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :fields, dependent: :destroy
  has_many :participations

  accepts_nested_attributes_for :fields, allow_destroy: true

  # regenerate token with `survey.regenerate_token`
  has_secure_token

  validates :name, presence: true

  def to_param
    token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  def create
    @survey = Survey.find(params.dig(:participation, :survey_id))
    @participation = Participation.new(participation_params)
    if @participation.save
      ActionCable.server.broadcast 'participation_channel', action: 'create', id: @participation.id, content: @participation.render
      @participation = Participation.new(survey: @survey)
    end
  end

  def destroy
    @participation = Participation.find(params[:id])
    if @participation.destroy
      ActionCable.server.broadcast 'participation_channel', action: 'destroy', id: @participation.id
    end
  end

  private

  def participation_params
    params.require(:participation).permit(:survey_id, answers: {})
  end
end

app/controllers/participations_controllerNEW.rb
class ParticipationsController < ApplicationController
  def create
    @survey = Survey.find(params.dig(:participation, :survey_id))
    @participation = Participation.new(participation_params)

    if @participation.save
      render json: { token: @survey.token, id: @participation.id }, status: :ok
      ActionCable.server.broadcast 'participation_channel', action: 'create', id: @participation.id, content: @participation.render
    else
      render json: @participation.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @participation = Participation.find(params[:id])
    if @participation.destroy
      render json: { token: @participation.survey.token }, status: :ok
      ActionCable.server.broadcast 'participation_channel', action: 'destroy', id: @participation.id
    end
  end

  private

  def participation_params
    params.require(:participation).permit(:survey_id, answers: {})
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: %i[show edit update destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @participation = Participation.new(survey: @survey)
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find_by(token: params[:token])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:name, :description, fields_attributes: [:id, :type, :name, :required, :_destroy, values: []])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whenever</title>
    <%= csrf_meta_tags %>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag    'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/participations/create.js.erb
App.clearParticipationForm()

app/views/surveys/_form.html.erb
<%= content_tag :div,
  id: "survey-form",
  data: {
    token: survey.token,
    survey: survey.to_json(except: [:id, :token, :created_at, :updated_at]),
    fields_attributes: survey.fields.order(:created_at).to_json(except: [:survey_id, :options, :created_at, :updated_at])
  } do %>
  <div class="pure-g">
    <div class="sidebar pure-u-1 pure-u-md-1-4">
      <div class="header">
        <h1>{{ survey.name }}</h1>
        <p>{{ survey.description }}</p>
      </div>
    </div>
    <div class="content pure-u-1 pure-u-md-3-4 pure-form pure-form-aligned">
      <legend>Einstellungen</legend>
      <fieldset>
        <div class="pure-control-group" v-bind:class="{ 'pure-form--error': $v.survey.name.$error }">
          <label>Name</label>
          <input
            type="text"
            class="pure-input-1-2"
            v-model="survey.name"
            @input="delayTouch($v.survey.name)"
          />
          <span class="pure-form--error" v-if="$v.survey.name.$error">muss ausgefüllt werden</span>
        </div>
        <div class="pure-control-group">
          <label>Description</label>
          <input
            type="text"
            class="pure-input-1-2"
            v-model="survey.description"
          />
        </div>
      </fieldset>
      <hr />
      <legend>Abfragen</legend>
      <fieldset v-for="(field, index) in survey.fields_attributes">
        <div v-if="field._destroy == '1'">
          <div class="pure-control-group">
            {{ field.name }} will be removed. <button class="pure-button" v-on:click="undoRemove(index)">Undo</button>
          </div>
        </div>
        <div v-else>
          <div class="pure-control-group">
            <label>Type</label>
            <select v-model="field.type" class="pure-input-1-2">
              <option
                v-for="type in types"
                v-bind:value="type.value">
                {{ type.name }}
              </option>
            </select>
          </div>
          <div class="pure-control-group" v-bind:class="{ 'pure-form--error': $v.survey.fields_attributes.$each[index].name.$error }">
            <label>Field Name</label>
            <input
              type="text"
              class="pure-input-1-2"
              v-model="field.name"
              @input="delayTouch($v.survey.fields_attributes.$each[index].name)"
            />
            <span class="pure-form--error" v-if="$v.survey.fields_attributes.$each[index].name.$error">muss ausgefüllt werden</span>
          </div>
          <input-tag v-if="field.type == 'select'" v-model="field.values" :tags="field.values" :label="'Werte'"></input-tag>
          <div class="pure-control-group">
            <label>Required</label>
            <select v-model="field.required">
              <option value="false">false</option>
              <option value="true">true</option>
            </select>
          </div>
          <button class="pure-button" v-on:click="removeField(index)">Remove</button>
        </div>

        <hr />
      </fieldset>

      <button v-on:click="addField">Add Field</button>

      <br />
      <button v-on:click="saveSurvey">Save Survey</button>
    </div>
  </div>
<% end %>

app/views/surveys/_participation.html.erb
<tr data-participation-id=<%= participation.id %>>
  <% participation.survey.fields.order(:created_at).each do |field| %>
    <td>
      <% if field.type == 'checkbox' %>
        <%= check_box_tag field.name, '1', participation.answers[field.name] == '1', onclick: 'return false;' %>
      <% else %>
        <%= participation.answers[field.name] %>
      <% end %>
    </td>
  <% end %>
  <td>
    <%= link_to 'Remove', participation_path(participation), method: :delete, class: 'pure-button', remote: true %>
  </td>
</tr>

app/views/surveys/_participation_form.html.erb
<%= form_with(model: participation) do |f| %>
  <%= f.hidden_field :survey_id, value: survey.id %>
  <%= f.fields_for :answers, OpenStruct.new(participation.answers) do |builder| %>
    <% survey.fields.order(:created_at).each do |field| %>
      <td>
        <%= render "surveys/fields/#{field.type}", field: field, f: builder, parent: f %>
      </td>
    <% end %>
  <% end %>
  <td><%= f.submit 'speichern', class: 'pure-button' %></td>
<% end %>

app/views/surveys/edit.html.erb
<%= render 'form', survey: @survey %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/fields/_checkbox.html.erb
<%= f.check_box field.name, required: field.required?, class: 'dynamic' %>

app/views/surveys/fields/_select.html.erb
<%= f.select field.name, field.values, { include_blank: true }, { required: field.required?, class: 'dynamic' } %>

app/views/surveys/fields/_text.html.erb
<%= f.text_field field.name, required: field.required?, class: 'dynamic' %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Surveys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.name %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<%= render 'form', survey: @survey %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<div class="pure-g">
  <div class="sidebar pure-u-1 pure-u-md-1-4">
    <div class="header">
      <h1><%= @survey.name %></h1>
      <p><%= @survey.description %></p>
      <%= link_to 'Edit', edit_survey_path(@survey), class: 'pure-button' %>
    </div>
  </div>
  <div class="content pure-u-1 pure-u-md-3-4">
    <p id="notice"><%= notice %></p>
    <div class="pure-form">
      <div class="responsive-table">
        <table>
          <thead>
            <tr>
              <% @survey.fields.order(:created_at).pluck("fields.name, fields.options ->> 'required'").each do |name, required| %>
                <th><%= '*' if required == 'true' %><%= name %></th>
              <% end %>
              <th></th>
            </tr>
          </thead>
          <tbody id="participations">
            <% @survey.participations.order(:created_at).each do |participation| %>
              <%= render 'participation', participation: participation %>
            <% end %>
          </tbody>
          <tfoot>
            <tr id="participation-form">
              <%= render 'participation_form', participation: @participation, survey: @survey %>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
</div>